# Inventaire statique — utilisé pour les TP4 et TP5
# ansible_connection=local : pas besoin de SSH, Ansible tourne sur la même machine

[local]
localhost ansible_connection=local

[webservers]
localhost ansible_connection=local
